### ISSUE TITLE
Transfer the repo to the Persian-Tools organization

### ISSUE THREAD

**Issue by ali-master** [rustland-fa/persian-tools-rs#8]
Hi @robatipoor 

I suggest you to transfer the repo to the Persian-Tools organization and if you are interested in, let me know to add you into the Organization.

Wish you all the best.
Ali

**Comment by robatipoor** [comment]
Unfortunately, the rust-fa community does not agree with this issue because it does not see any advantage If you are interested, you are free to clone this repository for your organization and do whatever you like
